//
// Generated file, do not edit! Created by nedtool 5.6 from packet/Packet.msg.
//

#ifndef __PACKET_M_H
#define __PACKET_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
    #include <vector>
    typedef std::vector<int> IntVector;
// }}

/**
 * Enum generated from <tt>packet/Packet.msg:8</tt> by nedtool.
 * <pre>
 * enum ALL_MSGS
 * {
 *     APP_MSG = 1;
 *     DATA_MSG = 2;
 *     FC_MSG = 3;
 *     SW_FLAG = 4;
 *     SETUP_MSG = 5;
 *     BUFLEN_MSG = 6;
 *     PATHLEN_MSG = 7;
 * }
 * </pre>
 */
enum ALL_MSGS {
    APP_MSG = 1,
    DATA_MSG = 2,
    FC_MSG = 3,
    SW_FLAG = 4,
    SETUP_MSG = 5,
    BUFLEN_MSG = 6,
    PATHLEN_MSG = 7
};

/**
 * Class generated from <tt>packet/Packet.msg:18</tt> by nedtool.
 * <pre>
 * message appMsg extends cPacket
 * {
 *     int srcLid;
 *     int dstLid;
 *     int msgId;
 *     int flitLength;//
 *     int pathLength; //
 * }
 * </pre>
 */
class appMsg : public ::omnetpp::cPacket
{
  protected:
    int srcLid;
    int dstLid;
    int msgId;
    int flitLength;
    int pathLength;

  private:
    void copy(const appMsg& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const appMsg&);

  public:
    appMsg(const char *name=nullptr, short kind=0);
    appMsg(const appMsg& other);
    virtual ~appMsg();
    appMsg& operator=(const appMsg& other);
    virtual appMsg *dup() const override {return new appMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getSrcLid() const;
    virtual void setSrcLid(int srcLid);
    virtual int getDstLid() const;
    virtual void setDstLid(int dstLid);
    virtual int getMsgId() const;
    virtual void setMsgId(int msgId);
    virtual int getFlitLength() const;
    virtual void setFlitLength(int flitLength);
    virtual int getPathLength() const;
    virtual void setPathLength(int pathLength);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const appMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, appMsg& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>packet/Packet.msg:28</tt> by nedtool.
 * <pre>
 * message dataMsg extends cPacket
 * {
 *     int srcLid;
 *     int dstLid;
 *     int msgId;
 *     int flitSn;
 *     int flitLength;
 *     int pathLength;  
 *     simtime_t curTime;
 * }
 * </pre>
 */
class dataMsg : public ::omnetpp::cPacket
{
  protected:
    int srcLid;
    int dstLid;
    int msgId;
    int flitSn;
    int flitLength;
    int pathLength;
    ::omnetpp::simtime_t curTime;

  private:
    void copy(const dataMsg& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const dataMsg&);

  public:
    dataMsg(const char *name=nullptr, short kind=0);
    dataMsg(const dataMsg& other);
    virtual ~dataMsg();
    dataMsg& operator=(const dataMsg& other);
    virtual dataMsg *dup() const override {return new dataMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getSrcLid() const;
    virtual void setSrcLid(int srcLid);
    virtual int getDstLid() const;
    virtual void setDstLid(int dstLid);
    virtual int getMsgId() const;
    virtual void setMsgId(int msgId);
    virtual int getFlitSn() const;
    virtual void setFlitSn(int flitSn);
    virtual int getFlitLength() const;
    virtual void setFlitLength(int flitLength);
    virtual int getPathLength() const;
    virtual void setPathLength(int pathLength);
    virtual ::omnetpp::simtime_t getCurTime() const;
    virtual void setCurTime(::omnetpp::simtime_t curTime);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const dataMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, dataMsg& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>packet/Packet.msg:40</tt> by nedtool.
 * <pre>
 * message SWFLAG extends cPacket
 * {
 *     int outPortNum;
 * }
 * </pre>
 */
class SWFLAG : public ::omnetpp::cPacket
{
  protected:
    int outPortNum;

  private:
    void copy(const SWFLAG& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const SWFLAG&);

  public:
    SWFLAG(const char *name=nullptr, short kind=0);
    SWFLAG(const SWFLAG& other);
    virtual ~SWFLAG();
    SWFLAG& operator=(const SWFLAG& other);
    virtual SWFLAG *dup() const override {return new SWFLAG(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getOutPortNum() const;
    virtual void setOutPortNum(int outPortNum);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const SWFLAG& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, SWFLAG& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>packet/Packet.msg:46</tt> by nedtool.
 * <pre>
 * message setupMsg extends cPacket
 * {
 *     int MEMSID;
 *     IntVector configuration;
 *     bool flag;
 *     bool ini;
 * 
 * 
 * }
 * </pre>
 */
class setupMsg : public ::omnetpp::cPacket
{
  protected:
    int MEMSID;
    IntVector configuration;
    bool flag;
    bool ini;

  private:
    void copy(const setupMsg& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const setupMsg&);

  public:
    setupMsg(const char *name=nullptr, short kind=0);
    setupMsg(const setupMsg& other);
    virtual ~setupMsg();
    setupMsg& operator=(const setupMsg& other);
    virtual setupMsg *dup() const override {return new setupMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getMEMSID() const;
    virtual void setMEMSID(int MEMSID);
    virtual IntVector& getConfiguration();
    virtual const IntVector& getConfiguration() const {return const_cast<setupMsg*>(this)->getConfiguration();}
    virtual void setConfiguration(const IntVector& configuration);
    virtual bool getFlag() const;
    virtual void setFlag(bool flag);
    virtual bool getIni() const;
    virtual void setIni(bool ini);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const setupMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, setupMsg& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>packet/Packet.msg:57</tt> by nedtool.
 * <pre>
 * message BufferLength extends cPacket
 * {
 *     int srcGroupIdx;
 *     IntVector bufLen;
 * }
 * </pre>
 */
class BufferLength : public ::omnetpp::cPacket
{
  protected:
    int srcGroupIdx;
    IntVector bufLen;

  private:
    void copy(const BufferLength& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const BufferLength&);

  public:
    BufferLength(const char *name=nullptr, short kind=0);
    BufferLength(const BufferLength& other);
    virtual ~BufferLength();
    BufferLength& operator=(const BufferLength& other);
    virtual BufferLength *dup() const override {return new BufferLength(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getSrcGroupIdx() const;
    virtual void setSrcGroupIdx(int srcGroupIdx);
    virtual IntVector& getBufLen();
    virtual const IntVector& getBufLen() const {return const_cast<BufferLength*>(this)->getBufLen();}
    virtual void setBufLen(const IntVector& bufLen);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const BufferLength& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, BufferLength& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>packet/Packet.msg:63</tt> by nedtool.
 * <pre>
 * message pathLength extends cPacket
 * {
 *     double recPathLength;
 * }
 * </pre>
 */
class pathLength : public ::omnetpp::cPacket
{
  protected:
    double recPathLength;

  private:
    void copy(const pathLength& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const pathLength&);

  public:
    pathLength(const char *name=nullptr, short kind=0);
    pathLength(const pathLength& other);
    virtual ~pathLength();
    pathLength& operator=(const pathLength& other);
    virtual pathLength *dup() const override {return new pathLength(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual double getRecPathLength() const;
    virtual void setRecPathLength(double recPathLength);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const pathLength& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, pathLength& obj) {obj.parsimUnpack(b);}


#endif // ifndef __PACKET_M_H

